baseURL = 'https://tumen2022.github.io'
languageCode = 'ru'
title = 'Тюменское дело'
theme = 'PaperMod'
defaultContentLanguage = "ru"


[outputs]
home = ["HTML", "RSS"]

[params]
author = "Группа поддержки по тюменскому делу"             
defaultTheme = "dark" 

description = "Сайт поддержки ребят по <<тюменскому делу>>"
og = "/img/og.png" 

[menu]
[[menu.main]]
    name = 'О деле'
    pageRef = '/about'
    weight = 20

[[menu.main]]
    name = 'Поддержать'
    pageRef = '/support'
    weight = 30
