baseURL = 'http://example.org/'
languageCode = 'ru'
title = 'Тюменское дело'
theme = 'PaperMod'
defaultContentLanguage = "ru"


[outputs]
home = ["HTML", "RSS"]

[params]
author = "Группа поддержки по тюменскому делу"                # You can also set author in post front matter individually
defaultTheme = "dark"              # default theme when first visit (auto|dark|light)

description = "A minimal Hugo theme with nice theme color."
og = "/img/og.png" 

[menu]
[[menu.main]]
    name = 'О деле'
    pageRef = '/about'
    weight = 20

[[menu.main]]
    name = 'Поддержать'
    pageRef = '/support'
    weight = 30
