baseURL = 'https://tumen2022.github.io'
languageCode = 'ru'
title = 'Тюменское дело'
theme = 'PaperMod'
defaultContentLanguage = "ru"


[outputs]
home = ["HTML", "RSS"]

[params]
author = "Группа поддержки по тюменскому делу"             
defaultTheme = "dark" 

description = "Сайт поддержки ребят по <<тюменскому делу>>"
og = "/img/og.png" 

[menu]
[[menu.main]]
    name = 'Новости'
    pageRef = '/news'
    weight = 10

[[menu.main]]
    name = 'О деле'
    pageRef = '/about'
    weight = 20

[[menu.main]]
    name = 'Фигуранты'
    pageRef = '/persons'
    weight = 30

[[menu.main]]
    name = 'Письма,рисунки,стихи '
    pageRef = '/letters'
    weight = 40


[[menu.main]]
    name = 'Поддержать'
    pageRef = '/help'
    weight = 50